# General Site settings
title: Photography Club
description: Uem's own photgraphy club managed by its skillful students
email: uemphotographyclub@gmail.com

#The navigation menu content
menu:
  - {name: Home, url: 'index.html'}
  - {name: Gallery, url: 'gallery.html'}
  - {name: Blogs, url: 'blogs.html'}
  - {name: About us, url: 'index.html/#about'}
  - {name: Contact, url: 'index.html/#contact'}


#gallery thumbnails:
thumbnails:
  - {name: bridge, folder: 'Proj1', url: '.jpg'}
  - {name: bulbs, folder: 'Proj2', url: 'thumb2.jpg'}
  - {name: cab, folder: 'Proj3', url: 'thumb3.jpg'}
  - {name: shadow, folder: 'Proj4', url: 'thumb4.jpg'}
  - {name: bunny, folder: 'Proj5', url: 'thumb5.jpg'}
  - {name: camera, folder: 'Proj6' ,url: 'thumb6.jpg'}
