# General Site settings
title: Photography Club
description: Uem's own photgraphy club managed by its skillful students
email: uemphotographyclub@gmail.com

#The navigation menu content
menu:
  - {name: Home, url: 'index.html'}
  - {name: Gallery, url: 'gallery.html'}
  - {name: Blogs, url: 'blogs.html'}
  - {name: About us, url: 'index.html/#about'}
  - {name: Contact, url: 'index.html/#contact'}


#ghome-allery thumbnails:
thumbnails:
  - {name: 'bridge', url: 'thumb1.jpg'}
  - {name: 'bulbs', url: 'thumb2.jpg'}
  - {name: 'cab', url: 'thumb3.jpg'}
  - {name: 'shadow', url: 'thumb4.jpg'}
  - {name: 'bunny', url: 'thumb5.jpg'}
  - {name: 'camera', url: 'thumb6.jpg'}

#main gallery thumbnails
gallery-thumbnails:
  - {name: alone}
  - {name: animalove}
  - {name: arora}
  - {name: beverage}
  - {name: books}
  - {name: butterfly}
  - {name: castle}
  - {name: cycle}
  - {name: eye}
  - {name: father}
  - {name: feast}
  - {name: girl}
  - {name: holi}
  - {name: music}
  - {name: shaadi}
  - {name: orangepop}
  - {name: rail}
  - {name: rayban}
  - {name: redpanda}
  - {name: sleep}
  - {name: tech}
  - {name: temple}
  - {name: urban}
  - {name: watch}
  - {name: waterfall}
  - {name: woods}
  - {name: bridge}
  - {name: bulbs}
  - {name: cab}
  - {name: shadow}
  - {name: bunny}
  - {name: camera}
