# General Site settings
title: Photography Club
description: Uem's own photgraphy club managed by its skillful students
email: uemphotographyclub@gmail.com

#The navigation menu content
menu:
  - {name: Home, url: 'index.html'}
  - {name: Gallery, url: 'gallery.html'}
  - {name: Blogs, url: 'blogs.html'}
  - {name: About us, url: 'index.html/#about'}
  - {name: Contact, url: 'index.html/#contact'}


#gallery thumbnails:
thumbnails:
  - {name: Typo International, folder: 'Proj1', url: 'img/thumb1.jpg'}
  - {name: American Apparel, folder: 'Proj2', url: 'img/thumb2.jpg'}
  - {name: Crisp Icons, folder: 'Proj3', url: 'img/thumb3.jpg'}
  - {name: Mobile UX/UI, folder: 'Proj4', url: 'img/thumb4.jpg'}
  - {name: Fresh beats, folder: 'Proj5', url: 'img/thumb5.jpg'}
  - {name: Timeline Page, folder: 'Proj6' ,url: 'img/thumb6.jpg'}
